image: mcr.microsoft.com/dotnet/sdk:latest

stages:
  - build
  - push
  - release
  
variables:
  BUILD_CONFIGURATION: 'Release'
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: '*/*/'
  
cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/project.assets.json'
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/*.csproj.nuget.*'
    - '$NUGET_PACKAGES_DIRECTORY'
  policy: pull-push

before_script:
  - 'docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY'
  
build:
  stage: build
  script:
    - 'docker build -t $CI_REGISTRY_IMAGE:dev -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -f WeddingShare/Dockerfile .'
    - 'docker push $CI_REGISTRY_IMAGE:dev'
    - 'docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA'
    
push_latest:
  variables:
    GIT_STRATEGY: none
  stage: push
  only:
    - main
    - master
  script:
    - 'docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA'
    - 'docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:latest'
    - 'docker push $CI_REGISTRY_IMAGE:latest'
    
push_tag:
  variables:
    GIT_STRATEGY: none
  stage: push
  only:
    - tags
  script:
    - 'docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA'
    - 'docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME'
    - 'docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME'
    - 'docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN $DOCKERHUB_REGISTRY'
    - 'docker images'
    - 'docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $DOCKERHUB_USERNAME/wedding_share:$CI_COMMIT_REF_NAME'
    - 'docker push $DOCKERHUB_USERNAME/wedding_share:$CI_COMMIT_REF_NAME'